#It is just a makefile

total.out:huo.o feng.o total.o
	./huo.o | ./feng.o |./total.o
huo.o:huo.c
	gcc huo.c -o huo.o
feng.o:feng.c
	gcc feng.c -o feng.o
total.o:total.c
	gcc total.c -o total.o
suanfa.out:suan.o
	./suan.o
suan.o:suanfa.c
	gcc suanfa.c -o suan.o
